### ISSUE TITLE
Idea for improvement

### ISSUE THREAD

**Issue by Packjackisback** [dekrypted/email-generator#1]
Currently it is random with the spread of "."s and numbers appended, but I think it would be a little bit easier to use if it gave simple emails first, so example@gmail.com, e.xample@gmail.com, and so on. There also is a small chance emails could repeat, so it would have to somehow have them saved. This tool isn't that necessary, as you just add "."s and +X, but good job! :D
I wasn't actually aware of the adding numbers trick. Thanks, and have a good thanksgiving!

**Comment by dekrypted** [comment]
Hey, that's actually a pretty cool idea! Thanks, I'll look into it.

And happy thanksgiving to you too! Enjoy your turkey day 🦃

**Comment by Maybechangethis** [comment]
Cringe Americans

**Comment by Packjackisback** [comment]
> Cringe Americans

Who hurt you?
